### PR TITLE
Add MIDI OUT feature (Win x64)

### PR DESCRIPTION
**Pull request by Nagitch**
(this PR is closed for change compare branch. to https://github.com/keijiro/MidiJack/pull/46)

Hi, I added MIDI Out feature (only Win x64) and examples for this.
implemented additional API, and MIDI Jack Window shows MIDI Out device and messages.

MIDI In API has no effect, even API specification. completely additional logic for code.

accordingly, project is migrated 2018.3.6f1 and README.md is modified.

thank you for care this PR with many changes. ;)

----

MIDI OUT の機能を実装しました。(Win x64のみ)
追加のAPIとサンプルシーン、MIDI Jack WindowにMIDI Out デバイスとメッセージが表示されるように修正しています。

元々のMIDI IN 機能に関しては影響を受けないように実装しています。もちろんですがMIDI INはAPI仕様に変更なく、MIDI OUTのロジックを追加する形で実装しています。
またそれに伴い、プロジェクトを 2018.3.6f1 にマイグレーションしたのと、
README.md もマージ後の内容に合わせて修正しました。

大幅な変更になるのでレビューが大変かと思いますが、動作確認含め見ていただけると嬉しいです。
よろしくお願いいたします。

### CODE REVIEW

**Comment by AndreaDiPiPietro** [comment]
Hello I'm really interested in making a VR Virtual Instrument using Reaktor, should I use a MIDI Bridge, make MidiJack recognize it and bridge the MidiJack messages to Reaktor for it to work? Or is there a more straightforward way to do so? If the first option is correct, do you recommend a functioning bridge that maybe you used to test out the Midi Out functions? Thanks for all the work, I appreciate every single effort you guys put into this!

**Comment by Nagitch** [comment]
Hi, I seemed the requirement for your project is send MIDI message from your VR application to Reaktor.
If Reaktor is recognized as MIDI OUT device with general DAW, this PR will help.

launch `Assets/Example Send/ExampleSend.unity`
In this PR, then select Midi out device to Reaktor and play with software keyboard is available, then might to be ready for advance.

Hope success :)

**Comment by AndreaDiPiPietro** [comment]
I managed to send MIDI messages from Unity to Reaktor using a MIDI bridge I downloaded, as Reaktor is not considered as a driver, but just as a program that receives or sends MIDI data. Interestingly enough if I play a note from a button in Unity it's fine, Reaktor sees the message and plays that note, if I input the message from, say, a keyboard, the message is recognized as a In and sent as an Out, but then feedbacks In and Out and crashes Unity and the MIDI bridge mutes itself as the result of a feedback. I still have to find a workaround for this (maybe muting the bridge as an input, but only an output?) Thanks for your reply! I'll probably update you on this github page for ableing me to make my graduation project :P

**Comment by Nagitch** [comment]
Bridge is needed for recognize Reaktor?
perhaps Reaktor throughs Midi in -> out and it causes feedback issue.

Happy for if it makes help you.

**Comment by AndreaDiPiPietro** [comment]
Yes it's needed, Reaktor does not have drivers, it's just an application as it may be Cubase.

**Comment by Nagitch** [comment]
close this PR for change compare branch. to https://github.com/keijiro/MidiJack/pull/46

**Comment by kymo-bit** [comment]
> I managed to send MIDI messages from Unity to Reaktor using a MIDI bridge I downloaded, as Reaktor is not considered as a driver, but just as a program that receives or sends MIDI data. Interestingly enough if I play a note from a button in Unity it's fine, Reaktor sees the message and plays that note, if I input the message from, say, a keyboard, the message is recognized as a In and sent as an Out, but then feedbacks In and Out and crashes Unity and the MIDI bridge mutes itself as the result of a feedback. I still have to find a workaround for this (maybe muting the bridge as an input, but only an output?) Thanks for your reply! I'll probably update you on this github page for ableing me to make my graduation project :P

Hi AndreaDiPiPietro,

I am trying to do the same thing in a project for fun!  I am not having much success.  Is there any way you could share a sample Unity scene so that I can figure it out?  I'm trying to send MIDI from Unity to my hardware synthesizer.  Thank you so much!

**Comment by AndreaDiPiPietro** [comment]
Hello! I’m answering you through email so I can keep better track of the conversation.
Right now I’m working as a Unity programmer so I don’t have a lot of time, and the last time I used that it was a lot of time ago.
I’ll try to download the git again and try to make something that works.

By the way, just to give you a hint, I remember it involved calling the MidiJack exposed functions (SendNote() and stuff like that, I don’t exactly remember) and passing the MIDI channel you need.
I think it actually has a list of MIDI devices it detected, so it’s a matter of choosing which one you want to use.
I’ll get back to you soon.

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

Da: kymo-bit<mailto:notifications@github.com>
Inviato: martedì 28 luglio 2020 00:29
A: keijiro/MidiJack<mailto:MidiJack@noreply.github.com>
Cc: AndreaDiPiPietro<mailto:dipietroandrea@hotmail.it>; Mention<mailto:mention@noreply.github.com>
Oggetto: Re: [keijiro/MidiJack] Add MIDI OUT feature (Win x64) (#40)


I managed to send MIDI messages from Unity to Reaktor using a MIDI bridge I downloaded, as Reaktor is not considered as a driver, but just as a program that receives or sends MIDI data. Interestingly enough if I play a note from a button in Unity it's fine, Reaktor sees the message and plays that note, if I input the message from, say, a keyboard, the message is recognized as a In and sent as an Out, but then feedbacks In and Out and crashes Unity and the MIDI bridge mutes itself as the result of a feedback. I still have to find a workaround for this (maybe muting the bridge as an input, but only an output?) Thanks for your reply! I'll probably update you on this github page for ableing me to make my graduation project :P

Hi AndreaDiPiPietro,

I am trying to do the same thing in a project for fun! I am not having much success. Is there any way you could share a sample Unity scene so that I can figure it out? I'm trying to send MIDI from Unity to my hardware synthesizer. Thank you so much!

**Comment by kymo-bit** [comment]
Hi

That's amazing!.

I am a designer so I am not great at code.


Any help you can provide would be great. Are you working at Unity now?   I
have a friend who works at Unity in Paris. Maybe you know each other?

Thank you so much.

Kyle

**Comment by AndreaDiPiPietro** [comment]
Ahah I work in a very small business in Rome, so that’s unlikely, I’m just a humble programmer who happens to (only) know Unity

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

Da: kymo-bit<mailto:notifications@github.com>
Inviato: martedì 28 luglio 2020 04:16
A: keijiro/MidiJack<mailto:MidiJack@noreply.github.com>
Cc: AndreaDiPiPietro<mailto:dipietroandrea@hotmail.it>; Mention<mailto:mention@noreply.github.com>
Oggetto: Re: [keijiro/MidiJack] Add MIDI OUT feature (Win x64) (#40)

Hi

That's amazing!.

I am a designer so I am not great at code.


Any help you can provide would be great. Are you working at Unity now? I
have a friend who works at Unity in Paris. Maybe you know each other?

Thank you so much.

Kyle

**Comment by kymo-bit** [comment]
Well perhaps if you are interested in relocating I can put you in touch
with Unity people in Paris

**Comment by AndreaDiPiPietro** [comment]
That would be great if I was an actually skilled programmer, I’m more inclined at working with audio, you know, recording, playing, composing.
I was using MidiJack to make a Virtual Reality Controlled VST, kinda of a new perspective on interfaces ahah

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

Da: kymo-bit<mailto:notifications@github.com>
Inviato: martedì 28 luglio 2020 04:20
A: keijiro/MidiJack<mailto:MidiJack@noreply.github.com>
Cc: AndreaDiPiPietro<mailto:dipietroandrea@hotmail.it>; Mention<mailto:mention@noreply.github.com>
Oggetto: Re: [keijiro/MidiJack] Add MIDI OUT feature (Win x64) (#40)

Well perhaps if you are interested in relocating I can put you in touch
with Unity people in Paris

**Comment by kymo-bit** [comment]
Yeah, that is what I am trying to do.  Use Unity + HoloLens 2 to interface
with hardware synths.

But I don't know how to set it up correctly.

I just want to use the Mixed Reality Toolkit and assign the sliders to the
faders on my Synthstrom Deluge.

**Comment by AndreaDiPiPietro** [comment]
Ok so I have experience with the Vive and the Index for now, so HMD + hand controllers. For the Hololens I don’t have any advice, BUT i would try to get into Steam VR asset because that’s the most advanced stuff I’ve seen Vr-wise on the asset store, and good documentation too

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

Da: kymo-bit<mailto:notifications@github.com>
Inviato: martedì 28 luglio 2020 04:28
A: keijiro/MidiJack<mailto:MidiJack@noreply.github.com>
Cc: AndreaDiPiPietro<mailto:dipietroandrea@hotmail.it>; Mention<mailto:mention@noreply.github.com>
Oggetto: Re: [keijiro/MidiJack] Add MIDI OUT feature (Win x64) (#40)

Yeah, that is what I am trying to do. Use Unity + HoloLens 2 to interface
with hardware synths.

But I don't know how to set it up correctly.

I just want to use the Mixed Reality Toolkit and assign the sliders to the
faders on my Synthstrom Deluge.

**Pull request closed without merging**
