### PR TITLE
iOS version and Xcode Target

### PR DESCRIPTION
**Pull request by jinkoandres**
Hi, I made an iOS target and changed the string for the plugin name so that it can be loaded again in unity. I didn't create a new unity package because I thought it would be better if you do it in the main repo and everyone updates it. Let me know if you can test it, it works in our devices here in the office

### CODE REVIEW

**Comment by jrmgx** [comment]
Hello, I'm very interested in this PR, I tried to get it working on iOS but I think I'm missing something  
This is the error message but I'm quite sure it is only because I missed a step in the setup
```
DllNotFoundException: Unable to load DLL 'MidiJackPlugin': The specified module could not be found.
  at MidiJack.MidiDriver.DequeueIncomingData () [0x00000] in <filename unknown>:0 
  at MidiJack.MidiDriver.Update () [0x00000] in <filename unknown>:0 
  at MidiJack.MidiDriver.UpdateIfNeeded () [0x00000] in <filename unknown>:0 
  at MidiJack.MidiDriver.GetKey (MidiChannel channel, Int32 noteNumber) [0x00000] in <filename unknown>:0 
  at NoteIndicator.Update () [0x00000] in <filename unknown>:0 
 
(Filename: currently not available on il2cpp Line: -1)
```
Any change you could come up with a little bit more detail on how to make it working?  
Thank you very much!

**Comment by jrmgx** [comment]
Ok I found out, for some reason the iOS plugin was not compiled when exporting the app to Xcode, doing it manually from your modified Xcode folder using your new iOS target (then putting the resulting file in the Plugins/iOS directory) worked :)

**Comment by monkydream** [comment]
jrmgx could you please go a little bit into the details of how you fixed this. I copied jinkoandres's MidiJackPlugin.bundle and libMidiJackPluginiOS.a to my Unity Plugin Folder and made the necessary settings in Unity's Plugin Import Settings Inspector. The plugins then get exported in my xcode project which compiles fine but I get the same Unable to load DLL 'MidiJackPlugin' error.

**Comment by MarkRob2nd** [comment]
I'm using MidiJack in my current project and it works very well so I would hate to change implementations at this juncture.  If we can get this into master, that would ideal.  I too wouldn't want to sustain a non-master branch of this amazing tool.

**Pull request closed without merging**
